COLUMN_NAMES = 'gx,gy,gz,ax,ay,az,roll,pitch,yaw,time_stamp,VideoRecord,DataRecord'.split(
    ',')

SAMPLE_FREQUENCY = 100

MAXIMUM_STROKE_RATE = 200

MINIMUM_TIME_PER_STROKE = 60.0/MAXIMUM_STROKE_RATE

MINIMUM_DISTANCE_BETWEEN_PEAKS = SAMPLE_FREQUENCY * MINIMUM_TIME_PER_STROKE
